## Benchmark for Reading and Datamining PDB Structures with mmtf-pyspark

In [1]:
from pyspark.sql import SparkSession
from mmtfPyspark.io import mmtfReader
from mmtfPyspark.filters import ContainsGroup
from mmtfPyspark.utils import ColumnarStructure
from mmtfPyspark.interactions import InteractionExtractorPd
import pandas as pd

import gzip
import pandas as pd
import numpy as np
import os
import time

In [2]:
spark = SparkSession.builder.master("local[1]").appName("RunPandasBenchmarks").getOrCreate()
#structures = mmtfReader.download_full_mmtf_files(['4HHB'])
structures = mmtfReader.download_full_mmtf_files(['3J3Q'])
dfs = structures.values().first()

In [ ]:
%time dfs.to_pandas()

In [3]:
%time dfs.chain_names                

CPU times: user 140 ms, sys: 35.1 ms, total: 175 ms
Wall time: 175 ms


array(['g8', 'g8', 'g8', ..., '9', '9', '9'], dtype=object)

In [4]:
%time dfs.chain_ids

CPU times: user 149 ms, sys: 42.5 ms, total: 192 ms
Wall time: 195 ms


array(['A', 'A', 'A', ..., 'DZA', 'DZA', 'DZA'], dtype=object)

In [5]:
%time dfs.group_numbers                       

CPU times: user 688 ms, sys: 16.7 ms, total: 705 ms
Wall time: 710 ms


array(['1', '1', '1', ..., '231', '231', '231'], dtype=object)

In [6]:
%time dfs.group_names                                

CPU times: user 404 ms, sys: 8.2 ms, total: 412 ms
Wall time: 414 ms


array(['PRO', 'PRO', 'PRO', ..., 'LEU', 'LEU', 'LEU'], dtype=object)

In [7]:
%time dfs.atom_names                                 

CPU times: user 544 ms, sys: 11.8 ms, total: 556 ms
Wall time: 628 ms


array(['N', 'CA', 'C', ..., 'CD1', 'CD2', 'OXT'], dtype=object)

In [8]:
%time dfs.alt_loc_list

CPU times: user 3.72 ms, sys: 4.11 ms, total: 7.83 ms
Wall time: 7.07 ms


array(['', '', '', ..., '', '', ''], dtype='<U1')

In [9]:
%time dfs.x_coord_list                             

CPU times: user 52.6 ms, sys: 25.3 ms, total: 77.9 ms
Wall time: 115 ms


array([393.23, 393.53, 393.05, ..., 272.63, 274.14, 269.46], dtype=float32)

In [10]:
%time dfs.y_coord_list                            

CPU times: user 54.6 ms, sys: 32.2 ms, total: 86.7 ms
Wall time: 100 ms


array([1016.3  , 1016.215, 1017.483, ..., 1046.202, 1044.589, 1043.473],
      dtype=float32)

In [11]:
%time dfs.z_coord_list                            

CPU times: user 39.6 ms, sys: 10 ms, total: 49.6 ms
Wall time: 53.9 ms


array([385.017, 383.535, 382.847, ..., 580.311, 581.334, 583.989],
      dtype=float32)

In [12]:
%time dfs.occupancy_list                            

CPU times: user 4.05 ms, sys: 4.23 ms, total: 8.28 ms
Wall time: 8.23 ms


array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [13]:
%time dfs.b_factor_list                        

CPU times: user 38.3 ms, sys: 10.2 ms, total: 48.4 ms
Wall time: 51.2 ms


array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [14]:
%time dfs.elements                     

CPU times: user 532 ms, sys: 5.21 ms, total: 538 ms
Wall time: 563 ms


array(['N', 'C', 'C', ..., 'C', 'C', 'O'], dtype=object)

In [15]:
%time dfs.polymer

CPU times: user 3.33 ms, sys: 2.78 ms, total: 6.11 ms
Wall time: 6.35 ms


array([ True,  True,  True, ...,  True,  True,  True])

In [16]:
%time dfs.code

CPU times: user 437 ms, sys: 2.22 ms, total: 439 ms
Wall time: 448 ms


In [14]:
%%time
df = pd.DataFrame({'chain_name': dfs.chain_names,
                                    'chain_id': dfs.chain_ids,
                                    'group_number': dfs.group_numbers,
                                    'group_name': dfs.group_names,
                                    'atom_name': dfs.atom_names,
                                    'altloc': dfs.alt_loc_list,
                                    'x': dfs.x_coord_list,
                                    'y': dfs.y_coord_list,
                                    'z': dfs.z_coord_list,
                                    'o': dfs.occupancy_list,
                                    'b': dfs.b_factor_list,
                                    'element': dfs.elements,
                                    'polymer:': dfs.polymer
                                    })

AttributeError: 'MmtfStructure' object has no attribute 'codec'

In [24]:
df

chain_name chain_id group_number group_name atom_name altloc  \
0               g8        A            1        PRO         N          
1               g8        A            1        PRO        CA          
2               g8        A            1        PRO         C          
3               g8        A            1        PRO         O          
4               g8        A            1        PRO        CB          
5               g8        A            1        PRO        CG          
6               g8        A            1        PRO        CD          
7               g8        A            2        ILE         N          
8               g8        A            2        ILE        CA          
9               g8        A            2        ILE         C          
10              g8        A            2        ILE         O          
11              g8        A            2        ILE        CB          
12              g8        A            2        ILE       CG1          
13              g8        A            2        ILE       CG2          
14              g8        A            2        ILE       CD1          
15              g8        A            3        VAL         N          
16              g8        A            3        VAL        CA          
17              g8        A            3        VAL         C          
18              g8        A            3        VAL         O          
19              g8        A            3        VAL        CB          
20              g8        A            3        VAL       CG1          
21              g8        A            3        VAL       CG2          
22              g8        A            4        GLN         N          
23              g8        A            4        GLN        CA          
24              g8        A            4        GLN         C          
25              g8        A            4        GLN         O          
26              g8        A            4        GLN        CB          
27              g8        A            4        GLN        CG          
28              g8        A            4        GLN        CD          
29              g8        A            4        GLN       OE1          
...            ...      ...          ...        ...       ...    ...   
2440770          9      DZA          228        ALA         C          
2440771          9      DZA          228        ALA         O          
2440772          9      DZA          228        ALA        CB          
2440773          9      DZA          229        ARG         N          
2440774          9      DZA          229        ARG        CA          
2440775          9      DZA          229        ARG         C          
2440776          9      DZA          229        ARG         O          
2440777          9      DZA          229        ARG        CB          
2440778          9      DZA          229        ARG        CG          
2440779          9      DZA          229        ARG        CD          
2440780          9      DZA          229        ARG        NE          
2440781          9      DZA          229        ARG        CZ          
2440782          9      DZA          229        ARG       NH1          
2440783          9      DZA          229        ARG       NH2          
2440784          9      DZA          230        VAL         N          
2440785          9      DZA          230        VAL        CA          
2440786          9      DZA          230        VAL         C          
2440787          9      DZA          230        VAL         O          
2440788          9      DZA          230        VAL        CB          
2440789          9      DZA          230        VAL       CG1          
2440790          9      DZA          230        VAL       CG2          
2440791          9      DZA          231        LEU         N          
2440792          9      DZA          231        LEU        CA          
2440793          9      DZA          231        

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2440800 entries, 0 to 2440799
Data columns (total 13 columns):
chain_name      category
chain_id        object
group_number    object
group_name      category
atom_name       category
altloc          category
x               float32
y               float32
z               float32
o               float32
b               float32
element         category
polymer:        bool
dtypes: bool(1), category(5), float32(5), object(2)
memory usage: 100.1+ MB


In [19]:
%%time
df['chain_name'] = df['chain_name'].astype('category')
df['group_name'] = df['group_name'].astype('category')
df['atom_name'] = df['atom_name'].astype('category')
df['element'] = df['element'].astype('category')

CPU times: user 154 ms, sys: 24.1 ms, total: 178 ms
Wall time: 182 ms


In [ ]:
df.info()

In [ ]:
df

In [16]:
spark.stop()